plugins: /verdaccio/plugins
storage: /verdaccio/storage
max_body_size: 100mb
auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
server:
  keepAliveTimeout: 0
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

middlewares:
  audit:
    enabled: true

packages:
  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    proxy: npmjs