version: '3'
services:
  verdaccio:
    image: verdaccio/verdaccio
    user: root
    restart: always
    ports:
      - "4873:4873"
    volumes:
        - ./storage:/verdaccio/storage
        - ./conf:/verdaccio/conf
        - ./plugins:/verdaccio/plugins
